function out = model
%
% MEC_Perfect.m
%
% Model exported on Jul 3 2019, 15:51 by COMSOL 5.3.0.316.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/Users/tm/Desktop/lab/reserch/mec/july/703');

model.comments([native2unicode(hex2dec({'71' '21'}), 'unicode')  native2unicode(hex2dec({'98' '4c'}), 'unicode') '\n\n']);

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');
model.study('std1').feature('stat').activate('solid', true);

model.component('comp1').geom('geom1').lengthUnit('nm');
model.component('comp1').geom('geom1').create('blk1', 'Block');
model.component('comp1').geom('geom1').feature('blk1').set('size', [52 52 100]);
model.component('comp1').geom('geom1').feature('blk1').setIndex('layer', 20, 0);
model.component('comp1').geom('geom1').feature('blk1').setIndex('layer', 1, 1);
model.component('comp1').geom('geom1').run('blk1');
model.component('comp1').geom('geom1').create('blk2', 'Block');
model.component('comp1').geom('geom1').feature('blk2').set('size', [10 10 20]);
model.component('comp1').geom('geom1').feature('blk2').set('pos', {'(52-10)/2' '(52-10)/2' '0'});
model.component('comp1').geom('geom1').feature('blk2').setIndex('pos', 20, 2);
model.component('comp1').geom('geom1').run('blk2');
model.component('comp1').geom('geom1').create('blk3', 'Block');
model.component('comp1').geom('geom1').feature('blk3').set('size', [12 12 20]);
model.component('comp1').geom('geom1').feature('blk3').set('pos', {'(52-12)/2' '(52-12)/2' '0'});
model.component('comp1').geom('geom1').feature('blk3').setIndex('pos', 21, 2);
model.component('comp1').geom('geom1').feature('blk3').setIndex('layer', 1, 0);
model.component('comp1').geom('geom1').run('blk3');
model.component('comp1').geom('geom1').feature.create('wp1', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp1').set('unite', true);
model.component('comp1').geom('geom1').feature('wp1').set('quickz', 20);
model.component('comp1').geom('geom1').feature('wp1').geom.create('sq1', 'Square');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq1').set('size', 42);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq1').set('pos', [5 5]);
model.component('comp1').geom('geom1').feature('wp1').geom.run('sq1');
model.component('comp1').geom('geom1').feature('wp1').geom.create('sq2', 'Square');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq2').set('size', 32);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq2').set('pos', [10 10]);
model.component('comp1').geom('geom1').feature('wp1').geom.run('sq2');
model.component('comp1').geom('geom1').feature('wp1').geom.create('sq3', 'Square');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq3').set('size', 22);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('sq3').set('pos', [15 15]);
model.component('comp1').geom('geom1').feature('wp1').geom.run('sq3');
model.component('comp1').geom('geom1').feature('wp1').geom.create('cha1', 'Chamfer');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('cha1').selection('point').set('sq1', [1 2 3 4]);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('cha1').selection('point').set('sq2', [1 2 3 4]);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('cha1').selection('point').set('sq3', [1 2 3 4]);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('cha1').set('dist', 3);
model.component('comp1').geom('geom1').run('wp1');
model.component('comp1').geom('geom1').feature.create('ext1', 'Extrude');
model.component('comp1').geom('geom1').run('ext1');

model.component('comp1').view('view1').set('transparency', true);

model.component('comp1').geom('geom1').feature('blk3').set('layertop', true);
model.component('comp1').geom('geom1').feature('blk3').set('layerbottom', false);
model.component('comp1').geom('geom1').run('blk3');
model.component('comp1').geom('geom1').runPre('fin');
model.component('comp1').geom('geom1').run;

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').selection.set([]);
model.component('comp1').material('mat1').label('copper');
model.component('comp1').material('mat1').selection.set([1 9 10]);
model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', {'129.3'});
model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', {'0.343'});
model.component('comp1').material('mat1').propertyGroup('def').set('density', {'8940'});
model.component('comp1').material.create('mat2', 'Common');
model.component('comp1').material('mat2').label('epoxy');
model.component('comp1').material('mat2').selection.set([3]);
model.component('comp1').material('mat2').propertyGroup('def').set('youngsmodulus', {'3'});
model.component('comp1').material('mat2').propertyGroup('def').set('poissonsratio', {'0.34'});
model.component('comp1').material('mat2').propertyGroup('def').set('density', {'1300'});
model.component('comp1').material.create('mat3', 'Common');
model.component('comp1').material('mat3').label('interface');
model.component('comp1').material('mat3').selection.set([7]);
model.component('comp1').material('mat3').propertyGroup('def').set('youngsmodulus', {'2.083'});
model.component('comp1').material('mat3').propertyGroup('def').set('poissonsratio', {'0.35'});
model.component('comp1').material('mat3').propertyGroup('def').set('density', {'1210'});
model.component('comp1').material.create('sw1', 'Switch');
model.component('comp1').material('sw1').selection.set([8]);
model.component('comp1').material('sw1').feature.create('mat1', 'Common', 'comp1');
model.component('comp1').material('sw1').feature.create('mat2', 'Common', 'comp1');
model.component('comp1').material('sw1').selection.set([]);
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('youngsmodulus', '');
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('poissonsratio', '');
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('density', '');
model.component('comp1').material('sw1').feature.remove('mat2');
model.component('comp1').material('sw1').feature.duplicate('mat2', 'mat1');
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('youngsmodulus', {'2.083'});
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('poissonsratio', {'0.35'});
model.component('comp1').material('sw1').feature('mat1').propertyGroup('def').set('density', {'1210'});
model.component('comp1').material('sw1').feature('mat2').propertyGroup('def').set('youngsmodulus', {'1*10^(-100)'});
model.component('comp1').material('sw1').feature('mat2').propertyGroup('def').set('poissonsratio', {'0.49'});
model.component('comp1').material('sw1').feature('mat2').propertyGroup('def').set('density', {'1210'});
model.component('comp1').material.duplicate('sw2', 'sw1');
model.component('comp1').material.duplicate('sw3', 'sw2');
model.component('comp1').material.duplicate('sw4', 'sw3');
model.component('comp1').material.duplicate('sw5', 'sw4');
model.component('comp1').material('sw1').selection.set([8]);
model.component('comp1').material('sw2').selection.set([6]);
model.component('comp1').material('sw3').selection.set([5]);
model.component('comp1').material('sw4').selection.set([4]);
model.component('comp1').material('sw5').selection.set([2]);

model.param.set('F', '1000[Pa]');
model.param.set('ssww1', '1');
model.param.set('ssww2', '1');
model.param.set('ssww3', '1');
model.param.set('ssww4', '1');
model.param.set('ssww5', '1');

model.component('comp1').physics('solid').create('fix1', 'Fixed', 2);
model.component('comp1').physics('solid').feature('fix1').selection.set([3]);
model.component('comp1').physics('solid').create('bndl1', 'BoundaryLoad', 2);
model.component('comp1').physics('solid').feature('bndl1').selection.set([10]);
model.component('comp1').physics('solid').feature('bndl1').set('LoadType', 'FollowerPressure');
model.component('comp1').physics('solid').feature('bndl1').set('FollowerPressure', '-F');
model.component('comp1').physics('solid').create('pc1', 'PeriodicCondition', 2);
model.component('comp1').physics('solid').feature('pc1').selection.set([1 4 7 66 67 68]);
model.component('comp1').physics('solid').create('pc2', 'PeriodicCondition', 2);
model.component('comp1').physics('solid').feature('pc2').selection.set([2 5 8 11 12 13]);

model.study('std1').create('param', 'Parametric');
model.study('std1').feature('param').setIndex('pname', 'F', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'F', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('plistarr', 'range(1,0.1,10)', 0);
model.study('std1').create('matsw', 'MaterialSweep');
model.study('std1').feature.move('matsw', 1);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw1', 0);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 0);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 0);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw1', 0);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 0);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 0);
model.study('std1').feature('matsw').setIndex('pcase', 'user', 0);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww1,1,2)', 0);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw2', 1);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 1);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 1);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw2', 1);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 1);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 1);
model.study('std1').feature('matsw').setIndex('pcase', 'user', 1);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww1,1,2)', 1);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw3', 2);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 2);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 2);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw3', 2);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 2);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 2);
model.study('std1').feature('matsw').setIndex('pcase', 'user', 2);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww1,1,2)', 2);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw4', 3);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 3);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw4', 3);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 3);
model.study('std1').feature('matsw').setIndex('pcase', 'user', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww1,1,2)', 3);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw5', 4);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 4);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 4);
model.study('std1').feature('matsw').setIndex('pname', 'matsw.comp1.sw5', 4);
model.study('std1').feature('matsw').setIndex('pcase', 'all', 4);
model.study('std1').feature('matsw').setIndex('plistarr', 'range(1,1,2)', 4);
model.study('std1').feature('matsw').setIndex('pcase', 'user', 4);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww5,1,2)', 4);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww5,1,2)', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww3,1,2)', 2);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww4,1,2)', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F>ssww2,1,2)', 1);

model.param.set('ssww1', '10');
model.param.set('ssww2', '10');
model.param.set('ssww3', '10');
model.param.set('ssww4', '10');
model.param.set('ssww5', '10');

model.sol.create('sol1');
model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.batch.create('pm1', 'MaterialSweep');
model.batch('pm1').study('std1');
model.batch('pm1').create('so1', 'Solutionseq');
model.batch('pm1').feature('so1').set('seq', 'sol1');
model.batch('pm1').feature('so1').set('store', 'on');
model.batch('pm1').feature('so1').set('clear', 'on');
model.batch('pm1').feature('so1').set('psol', 'none');
model.batch('pm1').set('pname', {'matsw.comp1.sw1' 'matsw.comp1.sw2' 'matsw.comp1.sw3' 'matsw.comp1.sw4' 'matsw.comp1.sw5'});
model.batch('pm1').set('plistarr', {'if(F>ssww1,1,2)' 'if(F>ssww2,1,2)' 'if(F>ssww3,1,2)' 'if(F>ssww4,1,2)' 'if(F>ssww5,1,2)'});
model.batch('pm1').set('sweeptype', 'filled');
model.batch('pm1').set('probesel', 'all');
model.batch('pm1').set('probes', {});
model.batch('pm1').set('plot', 'off');
model.batch('pm1').set('err', 'on');
model.batch('pm1').attach('std1');
model.batch('pm1').set('control', 'matsw');
model.batch.create('p1', 'Parametric');
model.batch('p1').study('std1');
model.batch('p1').create('jo1', 'Jobseq');
model.batch('p1').feature('jo1').set('seq', 'pm1');
model.batch('p1').set('pname', {'F'});
model.batch('p1').set('plistarr', {'range(1,0.1,10)'});
model.batch('p1').set('sweeptype', 'sparse');
model.batch('p1').set('err', 'on');
model.batch('p1').attach('std1');
model.batch('p1').set('control', 'param');

model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label([native2unicode(hex2dec({'30' 'd1'}), 'unicode')  native2unicode(hex2dec({'30' 'e9'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' 'c3'}), 'unicode')  native2unicode(hex2dec({'30' 'af'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);

model.batch('pm1').feature('so1').set('psol', 'sol2');

model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').set('data', 'dset2');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr', {'solid.mises'});
model.result('pg1').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid)']);
model.result('pg1').feature('surf1').create('def', 'Deform');
model.result('pg1').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg1').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.batch('p1').run;

model.result('pg1').run;

model.component('comp1').probe.create('bnd1', 'Boundary');
model.component('comp1').probe('bnd1').selection.set([10]);
model.component('comp1').probe('bnd1').label('most_upside');
model.component('comp1').probe.create('bnd2', 'Boundary');
model.component('comp1').probe('bnd2').selection.set([41]);
model.component('comp1').probe('bnd2').label('sw1_u');
model.component('comp1').probe.create('bnd3', 'Boundary');
model.component('comp1').probe('bnd3').selection.set([]);
model.component('comp1').probe('bnd3').label('sw1_d');
model.component('comp1').probe.duplicate('bnd4', 'bnd3');
model.component('comp1').probe.duplicate('bnd5', 'bnd4');
model.component('comp1').probe.duplicate('bnd6', 'bnd5');
model.component('comp1').probe.duplicate('bnd7', 'bnd6');
model.component('comp1').probe.duplicate('bnd8', 'bnd7');
model.component('comp1').probe.duplicate('bnd9', 'bnd8');
model.component('comp1').probe('bnd4').label('sw2_u');

model.component('comp1').view('view1').hideEntities.create('hide1');
model.component('comp1').view('view1').hideEntities('hide1').geom(2);
model.component('comp1').view('view1').hideEntities('hide1').add([10]);
model.component('comp1').view('view1').hideEntities.create('hide2');
model.component('comp1').view('view1').hideEntities('hide2').geom(3);
model.component('comp1').view('view1').hideEntities('hide2').add([3]);

model.component('comp1').probe('bnd3').selection.set([40 50]);
model.component('comp1').probe('bnd4').selection.set([31]);
model.component('comp1').probe('bnd5').label('sw2_d');
model.component('comp1').probe('bnd5').selection.set([30]);
model.component('comp1').probe('bnd6').label('sw3_d');
model.component('comp1').probe('bnd6').selection.set([24]);
model.component('comp1').probe('bnd6').label('sw3_u');
model.component('comp1').probe('bnd7').label('sw3_d');
model.component('comp1').probe('bnd7').selection.set([23]);
model.component('comp1').probe('bnd8').label('sw4_u');
model.component('comp1').probe('bnd9').label('sw4_d');
model.component('comp1').probe.duplicate('bnd10', 'bnd8');
model.component('comp1').probe.duplicate('bnd11', 'bnd9');
model.component('comp1').probe('bnd8').selection.set([17]);
model.component('comp1').probe('bnd9').selection.set([16]);
model.component('comp1').probe('bnd10').label('sw5_u');
model.component('comp1').probe('bnd10').selection.set([9]);
model.component('comp1').probe('bnd11').label('sw5_d');
model.component('comp1').probe('bnd11').selection.set([6]);

model.study('std1').feature('param').setIndex('plistarr', 'range(1,1,10)', 0);

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.create('pg2', 'PlotGroup3D');
model.result('pg2').set('data', 'dset1');
model.result('pg2').create('surf1', 'Surface');
model.result('pg2').feature('surf1').set('expr', {'solid.mises'});
model.result('pg2').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid) 1']);
model.result('pg2').feature('surf1').create('def', 'Deform');
model.result('pg2').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg2').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg2');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.create('pg4', 'PlotGroup3D');
model.result('pg4').set('data', 'dset1');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', {'solid.mises'});
model.result('pg4').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid) 1']);
model.result('pg4').feature('surf1').create('def', 'Deform');
model.result('pg4').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg4').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg4');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');

model.study('std1').feature('param').set('sweeptype', 'filled');

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.create('pg4', 'PlotGroup3D');
model.result('pg4').set('data', 'dset1');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', {'solid.mises'});
model.result('pg4').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid) 1']);
model.result('pg4').feature('surf1').create('def', 'Deform');
model.result('pg4').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg4').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg4');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');

model.study('std1').feature('param').setIndex('plistarr', 'range(1,1,10) range(1,1,10)', 0);
model.study('std1').feature.remove('param');
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F<ssww1,1,2)', 0);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F<ssww2,1,2)', 1);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F<ssww3,1,2)', 2);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F<ssww4,1,2)', 3);
model.study('std1').feature('matsw').setIndex('plistarr', 'if(F<ssww5,1,2)', 4);
model.study('std1').create('param', 'Parametric');
model.study('std1').feature('param').set('sweeptype', 'filled');
model.study('std1').feature('param').setIndex('pname', 'F', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'F', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('plistarr', 'range(0,1,10)', 0);

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.create('pg4', 'PlotGroup3D');
model.result('pg4').set('data', 'dset1');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', {'solid.mises'});
model.result('pg4').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid) 1']);
model.result('pg4').feature('surf1').create('def', 'Deform');
model.result('pg4').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg4').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg4');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');

model.label('MEC_Perfect.mph');

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.create('pg4', 'PlotGroup3D');
model.result('pg4').set('data', 'dset1');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', {'solid.mises'});
model.result('pg4').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid) 1']);
model.result('pg4').feature('surf1').create('def', 'Deform');
model.result('pg4').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg4').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg4');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');
model.result('pg3').set('window', 'window1');
model.result('pg3').run;
model.result('pg1').run;
model.result.dataset.remove('dset1');
model.result.dataset.remove('dset2');
model.result.dataset.remove('dset3');
model.result.table.remove('tbl1');

model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').feature.remove('s1');
model.sol('sol1').feature.remove('v1');
model.sol('sol1').feature.remove('st1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.result.dataset.create('dset1', 'Solution');
model.result.dataset('dset1').set('solution', 'sol1');
model.result.dataset.create('dset2', 'Solution');
model.result.dataset('dset2').set('solution', 'sol2');
model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').set('data', 'dset2');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr', {'solid.mises'});
model.result('pg1').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid)']);
model.result('pg1').feature('surf1').create('def', 'Deform');
model.result('pg1').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg1').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.result.remove('pg1');
model.result.numerical.remove('pev5');
model.result.numerical.remove('pev6');
model.result.numerical.remove('pev7');
model.result.numerical.remove('pev8');
model.result.numerical.remove('pev1');
model.result.numerical.remove('pev2');
model.result.numerical.remove('pev3');
model.result.numerical.remove('pev4');
model.result.numerical.remove('pev11');
model.result.numerical.remove('pev10');
model.result.numerical.remove('pev9');
model.result.dataset.remove('dset1');
model.result.dataset.remove('dset2');
model.result.dataset.remove('dset3');
model.result.table.remove('tbl1');

model.sol.remove('sol1');
model.sol.remove('sol2');

model.batch.remove('pm1');
model.batch.remove('p1');

model.sol.create('sol1');
model.sol('sol1').study('std1');

model.study('std1').feature('stat').set('notlistsolnum', 1);
model.study('std1').feature('stat').set('notsolnum', '1');
model.study('std1').feature('stat').set('listsolnum', 1);
model.study('std1').feature('stat').set('solnum', '1');

model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'stat');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'stat');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'mumps');
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'gmres');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 400);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').label([native2unicode(hex2dec({'63' 'd0'}), 'unicode')  native2unicode(hex2dec({'68' '48'}), 'unicode')  native2unicode(hex2dec({'30' '55'}), 'unicode')  native2unicode(hex2dec({'30' '8c'}), 'unicode')  native2unicode(hex2dec({'30' '8b'}), 'unicode')  native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5f' 'a9'}), 'unicode')  native2unicode(hex2dec({'30' 'bd'}), 'unicode')  native2unicode(hex2dec({'30' 'eb'}), 'unicode')  native2unicode(hex2dec({'30' 'd0'}), 'unicode')  native2unicode(hex2dec({'30' 'fc'}), 'unicode') ' (solid)']);
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'gmg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('termonres', 'auto');
model.sol('sol1').feature('s1').feature('fc1').set('reserrfact', 1000);
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').attach('std1');

model.batch.create('pm1', 'MaterialSweep');
model.batch('pm1').study('std1');
model.batch('pm1').create('so1', 'Solutionseq');
model.batch('pm1').feature('so1').set('seq', 'sol1');
model.batch('pm1').feature('so1').set('store', 'on');
model.batch('pm1').feature('so1').set('clear', 'on');
model.batch('pm1').feature('so1').set('psol', 'none');
model.batch('pm1').set('pname', {'matsw.comp1.sw1' 'matsw.comp1.sw2' 'matsw.comp1.sw3' 'matsw.comp1.sw4' 'matsw.comp1.sw5'});
model.batch('pm1').set('plistarr', {'if(F<ssww1,1,2)' 'if(F<ssww2,1,2)' 'if(F<ssww3,1,2)' 'if(F<ssww4,1,2)' 'if(F<ssww5,1,2)'});
model.batch('pm1').set('sweeptype', 'filled');
model.batch('pm1').set('probesel', 'all');
model.batch('pm1').set('probes', {'bnd1' 'bnd2' 'bnd3' 'bnd4' 'bnd5' 'bnd6' 'bnd7' 'bnd8' 'bnd9' 'bnd10'  ...
'bnd11'});
model.batch('pm1').set('plot', 'off');
model.batch('pm1').set('err', 'on');
model.batch('pm1').attach('std1');
model.batch('pm1').set('control', 'matsw');
model.batch.create('p1', 'Parametric');
model.batch('p1').study('std1');
model.batch('p1').create('jo1', 'Jobseq');
model.batch('p1').feature('jo1').set('seq', 'pm1');
model.batch('p1').set('pname', {'F'});
model.batch('p1').set('plistarr', {'range(0,1,10)'});
model.batch('p1').set('sweeptype', 'filled');
model.batch('p1').set('err', 'on');
model.batch('p1').attach('std1');
model.batch('p1').set('control', 'param');

model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label([native2unicode(hex2dec({'30' 'd1'}), 'unicode')  native2unicode(hex2dec({'30' 'e9'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' 'c3'}), 'unicode')  native2unicode(hex2dec({'30' 'af'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);

model.batch('pm1').feature('so1').set('psol', 'sol2');

model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').set('data', 'dset2');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr', {'solid.mises'});
model.result('pg1').label([native2unicode(hex2dec({'5f' 'dc'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (solid)']);
model.result('pg1').feature('surf1').create('def', 'Deform');
model.result('pg1').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg1').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'59' '09'}), 'unicode')  native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'58' '34'}), 'unicode') ' (' native2unicode(hex2dec({'72' '69'}), 'unicode')  native2unicode(hex2dec({'8c' 'ea'}), 'unicode')  native2unicode(hex2dec({'30' '4a'}), 'unicode')  native2unicode(hex2dec({'30' '88'}), 'unicode')  native2unicode(hex2dec({'30' '73'}), 'unicode')  native2unicode(hex2dec({'30' 'b8'}), 'unicode')  native2unicode(hex2dec({'30' 'aa'}), 'unicode')  native2unicode(hex2dec({'30' 'e1'}), 'unicode')  native2unicode(hex2dec({'30' 'c8'}), 'unicode')  native2unicode(hex2dec({'30' 'ea'}), 'unicode')  native2unicode(hex2dec({'5e' 'a7'}), 'unicode')  native2unicode(hex2dec({'6a' '19'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ')']);

model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');
model.component('comp1').probe('bnd1').genResult('none');
model.component('comp1').probe('bnd2').genResult('none');
model.component('comp1').probe('bnd3').genResult('none');
model.component('comp1').probe('bnd4').genResult('none');
model.component('comp1').probe('bnd5').genResult('none');
model.component('comp1').probe('bnd6').genResult('none');
model.component('comp1').probe('bnd7').genResult('none');
model.component('comp1').probe('bnd8').genResult('none');
model.component('comp1').probe('bnd9').genResult('none');
model.component('comp1').probe('bnd10').genResult('none');
model.component('comp1').probe('bnd11').genResult('none');

model.batch('p1').run;

model.result('pg1').run;
model.result('pg2').set('window', 'window1');
model.result('pg2').run;
model.result.export.create('tbl1', 'Table');
model.result.export('tbl1').set('filename', '/Users/tm/Desktop/lab/reserch/mec/july/703/test.csv');
model.result.export('tbl1').run;
model.result.export('tbl1').run;

out = model;
